### ISSUE TITLE
Could you please update this addon also work for the audible.it domain?

### ISSUE THREAD

**Issue by GFerrante** [peterphmikkelsen/audible-volume-control#2]
Unfortunately that isn't currently one of those the addon covers. Would be much appreciated. This addon is a lifesaver - unfortunately the Audible web player is extremely limited.

**Comment by peterphmikkelsen** [comment]
> Unfortunately that isn't currently one of those the addon covers. Would be much appreciated. This addon is a lifesaver - unfortunately the Audible web player is extremely limited.

Hi! Thank you for showing interest in the add-on! I have added the `https://www.audible.it` domain to the manifest👍Version 1.3 should already be available on Firefox and should come for Chromium based browsers soon (currently pending review - this should take less than 24 hours). Let me know if you have any issues 🙂
[28fea33](https://github.com/peterphmikkelsen/audible-volume-control/commit/28fea3384e1844254193e417cd87dc49bcca0759)

**Comment by GFerrante** [comment]
Thank you very much!

**Comment by peterphmikkelsen** [comment]
Hey @GFerrante! I have now changed the manifest and simplified the way I handle matches (see [ef8ee41](https://github.com/peterphmikkelsen/audible-volume-control/commit/ef8ee41e10235cf2e9bca6a361eefd849e9244d3)) so the extension should now work for all audible domains :+1: Please let me know if you run into any issues (currently it's only live for Firefox, since Google's review process is much slower for Chrome extensions).

**Comment by GFerrante** [comment]
Sounds great. Works like a charm for me.

**Comment by peterphmikkelsen** [comment]
> Sounds great. Works like a charm for me.
Great! Thanks 🙂
