### ISSUE TITLE
volume slider interpretation

### ISSUE THREAD

**Issue by dekdevy** [peterphmikkelsen/audible-volume-control#3]
Hey, great addon. Might want to change how the sliders value is interpreted:  
right now, the slider does very little up until you move it all the way to the left. the problem is described here:   
https://www.dr-lex.be/info-stuff/volumecontrols.html

**Comment by peterphmikkelsen** [comment]
Hey @dekdevy! I have just added this to the `main` branch 👍 Thanks for the tip (and also the cool article!). A new version with this change probably won't be released for a couple of days since I already have a version for Chrome in the pipeline (Chrome extensions take forever to review and approve 🙄)

**Comment by dekdevy** [comment]
nice!
